### ISSUE TITLE
It doesn't compile in 32 bits

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chen--oRanGe/nbds#3]
```
It doesn't compile in 32 bits (Debian 6.0).

First error:
runtime/runtime.c:27: error: ‘MaxThreadId’ undeclared (first use in this 
function)

The problem is in the previous line:
static int ThreadIndex
The line doesn't terminate with ';'

if ';' is added at the end of the line, still doesn't compile:

runtime/runtime.c:14: error: ‘ThreadIndex’ defined but not used

Solution: remove the line:
static int ThreadIndex


Second error:
test/perf_test.c:70: error: cast to pointer from integer of different size

The problem is in the line:
uint64_t ops = 0;

just substitute that line by:
#ifdef NBD32
    uint32_t ops = 0;
#else
    uint64_t ops = 0;
#endif

and then it compiles.
```

Original issue reported on code.google.com by `guido.re...@yahoo.com` on 15 Jun 2013 at 1:34
